const patients = [
  {
    id: 1,
    name: "Emma Chen",
    dob: "1990-04-12",
    payer: "Delta Dental",
    status: "EOB Available",
    benefits: {
      annualMax: 1500,
      remainingMax: 850,
      deductible: 50,
      deductibleRemaining: 0,
      preventive: "100%",
      basic: "80%",
      major: "50%",
      ortho: "Not covered",
    },
    eobs: [
      {
        id: "e1",
        date: "2026-03-10",
        code: "D2740",
        procedure: "Crown",
        billed: 1200,
        allowed: 850,
        paid: 425,
        patient: 425,
        status: "Processed",
        analysis: {
          reason: "Major service covered at 50%",
          issue: "High patient responsibility",
          suggestion: "Verify remaining max before treatment",
        },
      },
    ],
  },
  {
    id: 2,
    name: "Michael Patel",
    dob: "1985-09-22",
    payer: "Cigna",
    status: "Claim Denied",
    benefits: {
      annualMax: 2000,
      remainingMax: 2000,
      deductible: 100,
      deductibleRemaining: 100,
      preventive: "100%",
      basic: "70%",
      major: "50%",
      ortho: "50%",
    },
    eobs: [
      {
        id: "e2",
        date: "2026-02-15",
        code: "D4341",
        procedure: "Scaling and Root Planing",
        billed: 800,
        allowed: 0,
        paid: 0,
        patient: 800,
        status: "Denied",
        analysis: {
          reason: "Missing periodontal charting",
          issue: "Claim denied due to lack of documentation",
          suggestion: "Submit perio charting and resubmit claim",
        },
      },
    ],
  },
  {
    id: 3,
    name: "Sarah Johnson",
    dob: "1978-11-03",
    payer: "Aetna",
    status: "Eligibility Active",
    benefits: {
      annualMax: 2500,
      remainingMax: 2500,
      deductible: 75,
      deductibleRemaining: 75,
      preventive: "100%",
      basic: "80%",
      major: "60%",
      ortho: "50%",
    },
    eobs: [],
  },
];

module.exports = { patients };
